// flow-typed signature: d33f79b8418e81846d6b35c648483d1e
// flow-typed version: <<STUB>>/carbon-components_v8.16.8/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'carbon-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'carbon-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'carbon-components/es/bundle' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/accordion/accordion' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/card/card' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/carousel/carousel' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/checkbox/checkbox' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/content-switcher/content-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/copy-button/copy-button' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/data-table-v2/data-table-v2' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/data-table/data-table' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/date-picker/date-picker' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/detail-page-header/detail-page-header' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/dropdown/dropdown' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/fab/fab' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/file-uploader/file-uploader' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/floating-menu/floating-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/interior-left-nav/interior-left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/lightbox/lightbox' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/loading/loading' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/modal/modal' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/notification/notification' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/number-input/number-input' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/overflow-menu/overflow-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/progress-indicator/progress-indicator' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/search/search' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/slider/slider' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/structured-list/structured-list' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/tile/tile' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/toolbar/toolbar' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/unified-header/left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/es/components/unified-header/profile-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/boot' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/components' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/event-matches' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/get-launching-details' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/mixin' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/on' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/resize' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/misc/svg-toggle-class' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/create-component' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/evented-show-hide-state' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/evented-state' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/handles' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/init-component-by-event' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/init-component-by-launcher' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/init-component-by-search' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/mixins/track-blur' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/settings' {
  declare module.exports: any;
}

declare module 'carbon-components/es/globals/js/watch' {
  declare module.exports: any;
}

declare module 'carbon-components/es/index' {
  declare module.exports: any;
}

declare module 'carbon-components/scripts/carbon-components' {
  declare module.exports: any;
}

declare module 'carbon-components/scripts/carbon-components.min' {
  declare module.exports: any;
}

declare module 'carbon-components/src/bundle' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/accordion/accordion' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/card/card' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/carousel/carousel' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/checkbox/checkbox' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/content-switcher/content-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/copy-button/copy-button' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/data-table-v2/data-table-v2' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/data-table/data-table' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/date-picker/date-picker' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/detail-page-header/detail-page-header' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/dropdown/dropdown' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/fab/fab' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/file-uploader/file-uploader' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/floating-menu/floating-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/interior-left-nav/interior-left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/lightbox/lightbox' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/loading/loading' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/modal/modal' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/notification/notification' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/number-input/number-input' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/overflow-menu/overflow-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/progress-indicator/progress-indicator' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/search/search' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/slider/slider' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/structured-list/structured-list' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/tile/tile' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/toolbar/toolbar' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/unified-header/left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/src/components/unified-header/profile-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/boot' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/components' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/event-matches' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/get-launching-details' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/mixin' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/on' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/resize' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/misc/svg-toggle-class' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/create-component' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/evented-show-hide-state' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/evented-state' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/handles' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/init-component-by-event' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/init-component-by-launcher' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/init-component-by-search' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/mixins/track-blur' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/settings' {
  declare module.exports: any;
}

declare module 'carbon-components/src/globals/js/watch' {
  declare module.exports: any;
}

declare module 'carbon-components/src/index' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/bundle' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/accordion/accordion' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/card/card' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/carousel/carousel' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/checkbox/checkbox' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/content-switcher/content-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/copy-button/copy-button' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/data-table-v2/data-table-v2' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/data-table/data-table' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/date-picker/date-picker' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/detail-page-header/detail-page-header' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/dropdown/dropdown' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/fab/fab' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/file-uploader/file-uploader' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/floating-menu/floating-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/interior-left-nav/interior-left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/lightbox/lightbox' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/loading/loading' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/modal/modal' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/notification/notification' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/number-input/number-input' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/overflow-menu/overflow-menu' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/progress-indicator/progress-indicator' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/search/search' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/slider/slider' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/structured-list/structured-list' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/tile/tile' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/toolbar/toolbar' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/tooltip/tooltip' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/unified-header/left-nav' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/components/unified-header/profile-switcher' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/boot' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/components' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/event-matches' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/get-launching-details' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/mixin' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/on' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/resize' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/misc/svg-toggle-class' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/create-component' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/evented-show-hide-state' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/evented-state' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/handles' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/init-component-by-event' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/init-component-by-launcher' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/init-component-by-search' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/mixins/track-blur' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/settings' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/globals/js/watch' {
  declare module.exports: any;
}

declare module 'carbon-components/umd/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'carbon-components/es/bundle.js' {
  declare module.exports: $Exports<'carbon-components/es/bundle'>;
}
declare module 'carbon-components/es/components/accordion/accordion.js' {
  declare module.exports: $Exports<'carbon-components/es/components/accordion/accordion'>;
}
declare module 'carbon-components/es/components/card/card.js' {
  declare module.exports: $Exports<'carbon-components/es/components/card/card'>;
}
declare module 'carbon-components/es/components/carousel/carousel.js' {
  declare module.exports: $Exports<'carbon-components/es/components/carousel/carousel'>;
}
declare module 'carbon-components/es/components/checkbox/checkbox.js' {
  declare module.exports: $Exports<'carbon-components/es/components/checkbox/checkbox'>;
}
declare module 'carbon-components/es/components/content-switcher/content-switcher.js' {
  declare module.exports: $Exports<'carbon-components/es/components/content-switcher/content-switcher'>;
}
declare module 'carbon-components/es/components/copy-button/copy-button.js' {
  declare module.exports: $Exports<'carbon-components/es/components/copy-button/copy-button'>;
}
declare module 'carbon-components/es/components/data-table-v2/data-table-v2.js' {
  declare module.exports: $Exports<'carbon-components/es/components/data-table-v2/data-table-v2'>;
}
declare module 'carbon-components/es/components/data-table/data-table.js' {
  declare module.exports: $Exports<'carbon-components/es/components/data-table/data-table'>;
}
declare module 'carbon-components/es/components/date-picker/date-picker.js' {
  declare module.exports: $Exports<'carbon-components/es/components/date-picker/date-picker'>;
}
declare module 'carbon-components/es/components/detail-page-header/detail-page-header.js' {
  declare module.exports: $Exports<'carbon-components/es/components/detail-page-header/detail-page-header'>;
}
declare module 'carbon-components/es/components/dropdown/dropdown.js' {
  declare module.exports: $Exports<'carbon-components/es/components/dropdown/dropdown'>;
}
declare module 'carbon-components/es/components/fab/fab.js' {
  declare module.exports: $Exports<'carbon-components/es/components/fab/fab'>;
}
declare module 'carbon-components/es/components/file-uploader/file-uploader.js' {
  declare module.exports: $Exports<'carbon-components/es/components/file-uploader/file-uploader'>;
}
declare module 'carbon-components/es/components/floating-menu/floating-menu.js' {
  declare module.exports: $Exports<'carbon-components/es/components/floating-menu/floating-menu'>;
}
declare module 'carbon-components/es/components/interior-left-nav/interior-left-nav.js' {
  declare module.exports: $Exports<'carbon-components/es/components/interior-left-nav/interior-left-nav'>;
}
declare module 'carbon-components/es/components/lightbox/lightbox.js' {
  declare module.exports: $Exports<'carbon-components/es/components/lightbox/lightbox'>;
}
declare module 'carbon-components/es/components/loading/loading.js' {
  declare module.exports: $Exports<'carbon-components/es/components/loading/loading'>;
}
declare module 'carbon-components/es/components/modal/modal.js' {
  declare module.exports: $Exports<'carbon-components/es/components/modal/modal'>;
}
declare module 'carbon-components/es/components/notification/notification.js' {
  declare module.exports: $Exports<'carbon-components/es/components/notification/notification'>;
}
declare module 'carbon-components/es/components/number-input/number-input.js' {
  declare module.exports: $Exports<'carbon-components/es/components/number-input/number-input'>;
}
declare module 'carbon-components/es/components/overflow-menu/overflow-menu.js' {
  declare module.exports: $Exports<'carbon-components/es/components/overflow-menu/overflow-menu'>;
}
declare module 'carbon-components/es/components/pagination/pagination.js' {
  declare module.exports: $Exports<'carbon-components/es/components/pagination/pagination'>;
}
declare module 'carbon-components/es/components/progress-indicator/progress-indicator.js' {
  declare module.exports: $Exports<'carbon-components/es/components/progress-indicator/progress-indicator'>;
}
declare module 'carbon-components/es/components/search/search.js' {
  declare module.exports: $Exports<'carbon-components/es/components/search/search'>;
}
declare module 'carbon-components/es/components/slider/slider.js' {
  declare module.exports: $Exports<'carbon-components/es/components/slider/slider'>;
}
declare module 'carbon-components/es/components/structured-list/structured-list.js' {
  declare module.exports: $Exports<'carbon-components/es/components/structured-list/structured-list'>;
}
declare module 'carbon-components/es/components/tabs/tabs.js' {
  declare module.exports: $Exports<'carbon-components/es/components/tabs/tabs'>;
}
declare module 'carbon-components/es/components/tile/tile.js' {
  declare module.exports: $Exports<'carbon-components/es/components/tile/tile'>;
}
declare module 'carbon-components/es/components/toolbar/toolbar.js' {
  declare module.exports: $Exports<'carbon-components/es/components/toolbar/toolbar'>;
}
declare module 'carbon-components/es/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'carbon-components/es/components/tooltip/tooltip'>;
}
declare module 'carbon-components/es/components/unified-header/left-nav.js' {
  declare module.exports: $Exports<'carbon-components/es/components/unified-header/left-nav'>;
}
declare module 'carbon-components/es/components/unified-header/profile-switcher.js' {
  declare module.exports: $Exports<'carbon-components/es/components/unified-header/profile-switcher'>;
}
declare module 'carbon-components/es/globals/js/boot.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/boot'>;
}
declare module 'carbon-components/es/globals/js/components.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/components'>;
}
declare module 'carbon-components/es/globals/js/misc/event-matches.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/event-matches'>;
}
declare module 'carbon-components/es/globals/js/misc/get-launching-details.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/get-launching-details'>;
}
declare module 'carbon-components/es/globals/js/misc/mixin.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/mixin'>;
}
declare module 'carbon-components/es/globals/js/misc/on.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/on'>;
}
declare module 'carbon-components/es/globals/js/misc/resize.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/resize'>;
}
declare module 'carbon-components/es/globals/js/misc/svg-toggle-class.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/misc/svg-toggle-class'>;
}
declare module 'carbon-components/es/globals/js/mixins/create-component.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/create-component'>;
}
declare module 'carbon-components/es/globals/js/mixins/evented-show-hide-state.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/evented-show-hide-state'>;
}
declare module 'carbon-components/es/globals/js/mixins/evented-state.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/evented-state'>;
}
declare module 'carbon-components/es/globals/js/mixins/handles.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/handles'>;
}
declare module 'carbon-components/es/globals/js/mixins/init-component-by-event.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/init-component-by-event'>;
}
declare module 'carbon-components/es/globals/js/mixins/init-component-by-launcher.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/init-component-by-launcher'>;
}
declare module 'carbon-components/es/globals/js/mixins/init-component-by-search.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/init-component-by-search'>;
}
declare module 'carbon-components/es/globals/js/mixins/track-blur.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/mixins/track-blur'>;
}
declare module 'carbon-components/es/globals/js/settings.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/settings'>;
}
declare module 'carbon-components/es/globals/js/watch.js' {
  declare module.exports: $Exports<'carbon-components/es/globals/js/watch'>;
}
declare module 'carbon-components/es/index.js' {
  declare module.exports: $Exports<'carbon-components/es/index'>;
}
declare module 'carbon-components/scripts/carbon-components.js' {
  declare module.exports: $Exports<'carbon-components/scripts/carbon-components'>;
}
declare module 'carbon-components/scripts/carbon-components.min.js' {
  declare module.exports: $Exports<'carbon-components/scripts/carbon-components.min'>;
}
declare module 'carbon-components/src/bundle.js' {
  declare module.exports: $Exports<'carbon-components/src/bundle'>;
}
declare module 'carbon-components/src/components/accordion/accordion.js' {
  declare module.exports: $Exports<'carbon-components/src/components/accordion/accordion'>;
}
declare module 'carbon-components/src/components/card/card.js' {
  declare module.exports: $Exports<'carbon-components/src/components/card/card'>;
}
declare module 'carbon-components/src/components/carousel/carousel.js' {
  declare module.exports: $Exports<'carbon-components/src/components/carousel/carousel'>;
}
declare module 'carbon-components/src/components/checkbox/checkbox.js' {
  declare module.exports: $Exports<'carbon-components/src/components/checkbox/checkbox'>;
}
declare module 'carbon-components/src/components/content-switcher/content-switcher.js' {
  declare module.exports: $Exports<'carbon-components/src/components/content-switcher/content-switcher'>;
}
declare module 'carbon-components/src/components/copy-button/copy-button.js' {
  declare module.exports: $Exports<'carbon-components/src/components/copy-button/copy-button'>;
}
declare module 'carbon-components/src/components/data-table-v2/data-table-v2.js' {
  declare module.exports: $Exports<'carbon-components/src/components/data-table-v2/data-table-v2'>;
}
declare module 'carbon-components/src/components/data-table/data-table.js' {
  declare module.exports: $Exports<'carbon-components/src/components/data-table/data-table'>;
}
declare module 'carbon-components/src/components/date-picker/date-picker.js' {
  declare module.exports: $Exports<'carbon-components/src/components/date-picker/date-picker'>;
}
declare module 'carbon-components/src/components/detail-page-header/detail-page-header.js' {
  declare module.exports: $Exports<'carbon-components/src/components/detail-page-header/detail-page-header'>;
}
declare module 'carbon-components/src/components/dropdown/dropdown.js' {
  declare module.exports: $Exports<'carbon-components/src/components/dropdown/dropdown'>;
}
declare module 'carbon-components/src/components/fab/fab.js' {
  declare module.exports: $Exports<'carbon-components/src/components/fab/fab'>;
}
declare module 'carbon-components/src/components/file-uploader/file-uploader.js' {
  declare module.exports: $Exports<'carbon-components/src/components/file-uploader/file-uploader'>;
}
declare module 'carbon-components/src/components/floating-menu/floating-menu.js' {
  declare module.exports: $Exports<'carbon-components/src/components/floating-menu/floating-menu'>;
}
declare module 'carbon-components/src/components/interior-left-nav/interior-left-nav.js' {
  declare module.exports: $Exports<'carbon-components/src/components/interior-left-nav/interior-left-nav'>;
}
declare module 'carbon-components/src/components/lightbox/lightbox.js' {
  declare module.exports: $Exports<'carbon-components/src/components/lightbox/lightbox'>;
}
declare module 'carbon-components/src/components/loading/loading.js' {
  declare module.exports: $Exports<'carbon-components/src/components/loading/loading'>;
}
declare module 'carbon-components/src/components/modal/modal.js' {
  declare module.exports: $Exports<'carbon-components/src/components/modal/modal'>;
}
declare module 'carbon-components/src/components/notification/notification.js' {
  declare module.exports: $Exports<'carbon-components/src/components/notification/notification'>;
}
declare module 'carbon-components/src/components/number-input/number-input.js' {
  declare module.exports: $Exports<'carbon-components/src/components/number-input/number-input'>;
}
declare module 'carbon-components/src/components/overflow-menu/overflow-menu.js' {
  declare module.exports: $Exports<'carbon-components/src/components/overflow-menu/overflow-menu'>;
}
declare module 'carbon-components/src/components/pagination/pagination.js' {
  declare module.exports: $Exports<'carbon-components/src/components/pagination/pagination'>;
}
declare module 'carbon-components/src/components/progress-indicator/progress-indicator.js' {
  declare module.exports: $Exports<'carbon-components/src/components/progress-indicator/progress-indicator'>;
}
declare module 'carbon-components/src/components/search/search.js' {
  declare module.exports: $Exports<'carbon-components/src/components/search/search'>;
}
declare module 'carbon-components/src/components/slider/slider.js' {
  declare module.exports: $Exports<'carbon-components/src/components/slider/slider'>;
}
declare module 'carbon-components/src/components/structured-list/structured-list.js' {
  declare module.exports: $Exports<'carbon-components/src/components/structured-list/structured-list'>;
}
declare module 'carbon-components/src/components/tabs/tabs.js' {
  declare module.exports: $Exports<'carbon-components/src/components/tabs/tabs'>;
}
declare module 'carbon-components/src/components/tile/tile.js' {
  declare module.exports: $Exports<'carbon-components/src/components/tile/tile'>;
}
declare module 'carbon-components/src/components/toolbar/toolbar.js' {
  declare module.exports: $Exports<'carbon-components/src/components/toolbar/toolbar'>;
}
declare module 'carbon-components/src/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'carbon-components/src/components/tooltip/tooltip'>;
}
declare module 'carbon-components/src/components/unified-header/left-nav.js' {
  declare module.exports: $Exports<'carbon-components/src/components/unified-header/left-nav'>;
}
declare module 'carbon-components/src/components/unified-header/profile-switcher.js' {
  declare module.exports: $Exports<'carbon-components/src/components/unified-header/profile-switcher'>;
}
declare module 'carbon-components/src/globals/js/boot.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/boot'>;
}
declare module 'carbon-components/src/globals/js/components.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/components'>;
}
declare module 'carbon-components/src/globals/js/misc/event-matches.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/event-matches'>;
}
declare module 'carbon-components/src/globals/js/misc/get-launching-details.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/get-launching-details'>;
}
declare module 'carbon-components/src/globals/js/misc/mixin.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/mixin'>;
}
declare module 'carbon-components/src/globals/js/misc/on.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/on'>;
}
declare module 'carbon-components/src/globals/js/misc/resize.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/resize'>;
}
declare module 'carbon-components/src/globals/js/misc/svg-toggle-class.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/misc/svg-toggle-class'>;
}
declare module 'carbon-components/src/globals/js/mixins/create-component.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/create-component'>;
}
declare module 'carbon-components/src/globals/js/mixins/evented-show-hide-state.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/evented-show-hide-state'>;
}
declare module 'carbon-components/src/globals/js/mixins/evented-state.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/evented-state'>;
}
declare module 'carbon-components/src/globals/js/mixins/handles.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/handles'>;
}
declare module 'carbon-components/src/globals/js/mixins/init-component-by-event.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/init-component-by-event'>;
}
declare module 'carbon-components/src/globals/js/mixins/init-component-by-launcher.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/init-component-by-launcher'>;
}
declare module 'carbon-components/src/globals/js/mixins/init-component-by-search.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/init-component-by-search'>;
}
declare module 'carbon-components/src/globals/js/mixins/track-blur.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/mixins/track-blur'>;
}
declare module 'carbon-components/src/globals/js/settings.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/settings'>;
}
declare module 'carbon-components/src/globals/js/watch.js' {
  declare module.exports: $Exports<'carbon-components/src/globals/js/watch'>;
}
declare module 'carbon-components/src/index.js' {
  declare module.exports: $Exports<'carbon-components/src/index'>;
}
declare module 'carbon-components/umd/bundle.js' {
  declare module.exports: $Exports<'carbon-components/umd/bundle'>;
}
declare module 'carbon-components/umd/components/accordion/accordion.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/accordion/accordion'>;
}
declare module 'carbon-components/umd/components/card/card.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/card/card'>;
}
declare module 'carbon-components/umd/components/carousel/carousel.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/carousel/carousel'>;
}
declare module 'carbon-components/umd/components/checkbox/checkbox.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/checkbox/checkbox'>;
}
declare module 'carbon-components/umd/components/content-switcher/content-switcher.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/content-switcher/content-switcher'>;
}
declare module 'carbon-components/umd/components/copy-button/copy-button.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/copy-button/copy-button'>;
}
declare module 'carbon-components/umd/components/data-table-v2/data-table-v2.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/data-table-v2/data-table-v2'>;
}
declare module 'carbon-components/umd/components/data-table/data-table.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/data-table/data-table'>;
}
declare module 'carbon-components/umd/components/date-picker/date-picker.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/date-picker/date-picker'>;
}
declare module 'carbon-components/umd/components/detail-page-header/detail-page-header.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/detail-page-header/detail-page-header'>;
}
declare module 'carbon-components/umd/components/dropdown/dropdown.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/dropdown/dropdown'>;
}
declare module 'carbon-components/umd/components/fab/fab.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/fab/fab'>;
}
declare module 'carbon-components/umd/components/file-uploader/file-uploader.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/file-uploader/file-uploader'>;
}
declare module 'carbon-components/umd/components/floating-menu/floating-menu.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/floating-menu/floating-menu'>;
}
declare module 'carbon-components/umd/components/interior-left-nav/interior-left-nav.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/interior-left-nav/interior-left-nav'>;
}
declare module 'carbon-components/umd/components/lightbox/lightbox.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/lightbox/lightbox'>;
}
declare module 'carbon-components/umd/components/loading/loading.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/loading/loading'>;
}
declare module 'carbon-components/umd/components/modal/modal.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/modal/modal'>;
}
declare module 'carbon-components/umd/components/notification/notification.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/notification/notification'>;
}
declare module 'carbon-components/umd/components/number-input/number-input.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/number-input/number-input'>;
}
declare module 'carbon-components/umd/components/overflow-menu/overflow-menu.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/overflow-menu/overflow-menu'>;
}
declare module 'carbon-components/umd/components/pagination/pagination.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/pagination/pagination'>;
}
declare module 'carbon-components/umd/components/progress-indicator/progress-indicator.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/progress-indicator/progress-indicator'>;
}
declare module 'carbon-components/umd/components/search/search.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/search/search'>;
}
declare module 'carbon-components/umd/components/slider/slider.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/slider/slider'>;
}
declare module 'carbon-components/umd/components/structured-list/structured-list.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/structured-list/structured-list'>;
}
declare module 'carbon-components/umd/components/tabs/tabs.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/tabs/tabs'>;
}
declare module 'carbon-components/umd/components/tile/tile.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/tile/tile'>;
}
declare module 'carbon-components/umd/components/toolbar/toolbar.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/toolbar/toolbar'>;
}
declare module 'carbon-components/umd/components/tooltip/tooltip.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/tooltip/tooltip'>;
}
declare module 'carbon-components/umd/components/unified-header/left-nav.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/unified-header/left-nav'>;
}
declare module 'carbon-components/umd/components/unified-header/profile-switcher.js' {
  declare module.exports: $Exports<'carbon-components/umd/components/unified-header/profile-switcher'>;
}
declare module 'carbon-components/umd/globals/js/boot.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/boot'>;
}
declare module 'carbon-components/umd/globals/js/components.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/components'>;
}
declare module 'carbon-components/umd/globals/js/misc/event-matches.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/event-matches'>;
}
declare module 'carbon-components/umd/globals/js/misc/get-launching-details.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/get-launching-details'>;
}
declare module 'carbon-components/umd/globals/js/misc/mixin.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/mixin'>;
}
declare module 'carbon-components/umd/globals/js/misc/on.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/on'>;
}
declare module 'carbon-components/umd/globals/js/misc/resize.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/resize'>;
}
declare module 'carbon-components/umd/globals/js/misc/svg-toggle-class.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/misc/svg-toggle-class'>;
}
declare module 'carbon-components/umd/globals/js/mixins/create-component.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/create-component'>;
}
declare module 'carbon-components/umd/globals/js/mixins/evented-show-hide-state.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/evented-show-hide-state'>;
}
declare module 'carbon-components/umd/globals/js/mixins/evented-state.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/evented-state'>;
}
declare module 'carbon-components/umd/globals/js/mixins/handles.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/handles'>;
}
declare module 'carbon-components/umd/globals/js/mixins/init-component-by-event.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/init-component-by-event'>;
}
declare module 'carbon-components/umd/globals/js/mixins/init-component-by-launcher.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/init-component-by-launcher'>;
}
declare module 'carbon-components/umd/globals/js/mixins/init-component-by-search.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/init-component-by-search'>;
}
declare module 'carbon-components/umd/globals/js/mixins/track-blur.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/mixins/track-blur'>;
}
declare module 'carbon-components/umd/globals/js/settings.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/settings'>;
}
declare module 'carbon-components/umd/globals/js/watch.js' {
  declare module.exports: $Exports<'carbon-components/umd/globals/js/watch'>;
}
declare module 'carbon-components/umd/index.js' {
  declare module.exports: $Exports<'carbon-components/umd/index'>;
}
