// flow-typed signature: 056f0e7dca8f7d60d4646a98ed3ca424
// flow-typed version: <<STUB>>/custom-react-scripts_v0.2.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'custom-react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'custom-react-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'custom-react-scripts/bin/react-scripts' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/config' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/customizers/babel-plugins' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/customizers/babel-presets' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/customizers/webpack-loaders' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/customizers/webpack-plugins' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/options/extract-text-plugin-options' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/options/postcss-options' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/utils/map-object' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/custom-react-scripts/webpack-config/style-loader' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/env' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/paths' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/polyfills' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/build' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/eject' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/getProcessForPort' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/init' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/modify-readmes' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/start' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/test' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/scripts/utils/createJestConfig' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/template/src/App' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/template/src/App.test' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/template/src/Emoji' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/template/src/index' {
  declare module.exports: any;
}

declare module 'custom-react-scripts/template/src/registerServiceWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'custom-react-scripts/bin/react-scripts.js' {
  declare module.exports: $Exports<'custom-react-scripts/bin/react-scripts'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/config.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/config'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/customizers/babel-plugins.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/customizers/babel-plugins'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/customizers/babel-presets.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/customizers/babel-presets'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/customizers/webpack-loaders.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/customizers/webpack-loaders'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/customizers/webpack-plugins.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/customizers/webpack-plugins'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/options/extract-text-plugin-options.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/options/extract-text-plugin-options'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/options/postcss-options.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/options/postcss-options'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/utils/map-object.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/utils/map-object'>;
}
declare module 'custom-react-scripts/config/custom-react-scripts/webpack-config/style-loader.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/custom-react-scripts/webpack-config/style-loader'>;
}
declare module 'custom-react-scripts/config/env.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/env'>;
}
declare module 'custom-react-scripts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/jest/babelTransform'>;
}
declare module 'custom-react-scripts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/jest/cssTransform'>;
}
declare module 'custom-react-scripts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/jest/fileTransform'>;
}
declare module 'custom-react-scripts/config/paths.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/paths'>;
}
declare module 'custom-react-scripts/config/polyfills.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/polyfills'>;
}
declare module 'custom-react-scripts/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/webpack.config.dev'>;
}
declare module 'custom-react-scripts/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/webpack.config.prod'>;
}
declare module 'custom-react-scripts/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'custom-react-scripts/config/webpackDevServer.config'>;
}
declare module 'custom-react-scripts/scripts/build.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/build'>;
}
declare module 'custom-react-scripts/scripts/eject.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/eject'>;
}
declare module 'custom-react-scripts/scripts/getProcessForPort.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/getProcessForPort'>;
}
declare module 'custom-react-scripts/scripts/init.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/init'>;
}
declare module 'custom-react-scripts/scripts/modify-readmes.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/modify-readmes'>;
}
declare module 'custom-react-scripts/scripts/start.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/start'>;
}
declare module 'custom-react-scripts/scripts/test.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/test'>;
}
declare module 'custom-react-scripts/scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'custom-react-scripts/scripts/utils/createJestConfig'>;
}
declare module 'custom-react-scripts/template/src/App.js' {
  declare module.exports: $Exports<'custom-react-scripts/template/src/App'>;
}
declare module 'custom-react-scripts/template/src/App.test.js' {
  declare module.exports: $Exports<'custom-react-scripts/template/src/App.test'>;
}
declare module 'custom-react-scripts/template/src/Emoji.js' {
  declare module.exports: $Exports<'custom-react-scripts/template/src/Emoji'>;
}
declare module 'custom-react-scripts/template/src/index.js' {
  declare module.exports: $Exports<'custom-react-scripts/template/src/index'>;
}
declare module 'custom-react-scripts/template/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'custom-react-scripts/template/src/registerServiceWorker'>;
}
