// flow-typed signature: 3fe0846ce03313b02feb27bf3baba41e
// flow-typed version: <<STUB>>/eslint-plugin-polymath-react_vgithub:PolymathNetwork/eslint-plugin-polymath-react#master/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-polymath-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-polymath-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-polymath-react/config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-polymath-react/config.js' {
  declare module.exports: $Exports<'eslint-plugin-polymath-react/config'>;
}
declare module 'eslint-plugin-polymath-react/index' {
  declare module.exports: $Exports<'eslint-plugin-polymath-react'>;
}
declare module 'eslint-plugin-polymath-react/index.js' {
  declare module.exports: $Exports<'eslint-plugin-polymath-react'>;
}
