// flow-typed signature: 06313cfb8a981f789088b23edea64689
// flow-typed version: <<STUB>>/polymath-auth_v1.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymath-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymath-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymath-auth/dist/actions' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/helpers' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/index' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/networks' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/PolymathAuth' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/reducer' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/redux/helpers' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/redux/network/actions' {
  declare module.exports: any;
}

declare module 'polymath-auth/dist/redux/network/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymath-auth/dist/actions.js' {
  declare module.exports: $Exports<'polymath-auth/dist/actions'>;
}
declare module 'polymath-auth/dist/helpers.js' {
  declare module.exports: $Exports<'polymath-auth/dist/helpers'>;
}
declare module 'polymath-auth/dist/index.js' {
  declare module.exports: $Exports<'polymath-auth/dist/index'>;
}
declare module 'polymath-auth/dist/networks.js' {
  declare module.exports: $Exports<'polymath-auth/dist/networks'>;
}
declare module 'polymath-auth/dist/PolymathAuth.js' {
  declare module.exports: $Exports<'polymath-auth/dist/PolymathAuth'>;
}
declare module 'polymath-auth/dist/reducer.js' {
  declare module.exports: $Exports<'polymath-auth/dist/reducer'>;
}
declare module 'polymath-auth/dist/redux/helpers.js' {
  declare module.exports: $Exports<'polymath-auth/dist/redux/helpers'>;
}
declare module 'polymath-auth/dist/redux/network/actions.js' {
  declare module.exports: $Exports<'polymath-auth/dist/redux/network/actions'>;
}
declare module 'polymath-auth/dist/redux/network/reducer.js' {
  declare module.exports: $Exports<'polymath-auth/dist/redux/network/reducer'>;
}
