// flow-typed signature: c51dd5043bc0f3ddd29f08f2a617f1f1
// flow-typed version: <<STUB>>/polymath-ui_v0.1.8/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymath-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymath-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymath-ui/dist/components/inputs' {
  declare module.exports: any;
}

declare module 'polymath-ui/dist/components/toaster' {
  declare module.exports: any;
}

declare module 'polymath-ui/dist/index' {
  declare module.exports: any;
}

declare module 'polymath-ui/dist/inputs' {
  declare module.exports: any;
}

declare module 'polymath-ui/dist/validate' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/babel-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/carbon-components_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/carbon-components-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/carbon-icons_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/eslint-plugin-polymath_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/eslint-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/node-sass-chokidar_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/npm-run-all_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/react-transition-group_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/sass-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymath-ui/src/components/inputs' {
  declare module.exports: any;
}

declare module 'polymath-ui/src/components/toaster' {
  declare module.exports: any;
}

declare module 'polymath-ui/src/index' {
  declare module.exports: any;
}

declare module 'polymath-ui/src/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymath-ui/dist/components/inputs.js' {
  declare module.exports: $Exports<'polymath-ui/dist/components/inputs'>;
}
declare module 'polymath-ui/dist/components/toaster.js' {
  declare module.exports: $Exports<'polymath-ui/dist/components/toaster'>;
}
declare module 'polymath-ui/dist/index.js' {
  declare module.exports: $Exports<'polymath-ui/dist/index'>;
}
declare module 'polymath-ui/dist/inputs.js' {
  declare module.exports: $Exports<'polymath-ui/dist/inputs'>;
}
declare module 'polymath-ui/dist/validate.js' {
  declare module.exports: $Exports<'polymath-ui/dist/validate'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/babel-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/babel-runtime_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/carbon-components_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/carbon-components_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/carbon-components-react_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/carbon-components-react_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/carbon-icons_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/carbon-icons_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/eslint-plugin-polymath_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/eslint-plugin-polymath_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/eslint-watch_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/eslint-watch_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/node-sass-chokidar_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/node-sass-chokidar_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/npm-run-all_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/npm-run-all_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/react-transition-group_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/react-transition-group_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/sass-loader_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/sass-loader_vx.x.x'>;
}
declare module 'polymath-ui/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'polymath-ui/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module 'polymath-ui/src/components/inputs.js' {
  declare module.exports: $Exports<'polymath-ui/src/components/inputs'>;
}
declare module 'polymath-ui/src/components/toaster.js' {
  declare module.exports: $Exports<'polymath-ui/src/components/toaster'>;
}
declare module 'polymath-ui/src/index.js' {
  declare module.exports: $Exports<'polymath-ui/src/index'>;
}
declare module 'polymath-ui/src/validate.js' {
  declare module.exports: $Exports<'polymath-ui/src/validate'>;
}
