// flow-typed signature: 808c215022384d97a5bfc1cbc115a26c
// flow-typed version: <<STUB>>/polymath.js_v2_v0.1.9/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymath.js_v2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymath.js_v2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymath.js_v2/dist/contracts/Contract' {
  declare module.exports: any;
}

declare module 'polymath.js_v2/dist/contracts/PolyToken' {
  declare module.exports: any;
}

declare module 'polymath.js_v2/dist/contracts/SecurityTokenRegistrar' {
  declare module.exports: any;
}

declare module 'polymath.js_v2/dist/contracts/types' {
  declare module.exports: any;
}

declare module 'polymath.js_v2/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymath.js_v2/dist/contracts/Contract.js' {
  declare module.exports: $Exports<'polymath.js_v2/dist/contracts/Contract'>;
}
declare module 'polymath.js_v2/dist/contracts/PolyToken.js' {
  declare module.exports: $Exports<'polymath.js_v2/dist/contracts/PolyToken'>;
}
declare module 'polymath.js_v2/dist/contracts/SecurityTokenRegistrar.js' {
  declare module.exports: $Exports<'polymath.js_v2/dist/contracts/SecurityTokenRegistrar'>;
}
declare module 'polymath.js_v2/dist/contracts/types.js' {
  declare module.exports: $Exports<'polymath.js_v2/dist/contracts/types'>;
}
declare module 'polymath.js_v2/dist/index.js' {
  declare module.exports: $Exports<'polymath.js_v2/dist/index'>;
}
