// flow-typed signature: 485a652fc6a811d954b43c81df153ef3
// flow-typed version: <<STUB>>/polymathjs_v1.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polymathjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polymathjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polymathjs/dist/contracts/CappedSTOFactory' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/Contract' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/PermissionManager' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/PolyToken' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/SecurityToken' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/SecurityTokenRegistrar' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/SecurityTokenRegistry' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/STO' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/TickerRegistrar' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/TickerRegistry' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/TransferManager' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/contracts/types' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/index' {
  declare module.exports: any;
}

declare module 'polymathjs/dist/IPFS' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/axios_v0.16.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/bignumber.js_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/eslint-plugin-polymath_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/npm-run-all_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/polymath-core_v2_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/redux-thunk_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/web3_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/web3-core-method_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/flow-typed/npm/web3-eth-contract_vx.x.x' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/CappedSTOFactory' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/Contract' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/PermissionManager' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/PolyToken' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/SecurityToken' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/SecurityTokenRegistry' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/STO' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/TickerRegistry' {
  declare module.exports: any;
}

declare module 'polymathjs/src/contracts/TransferManager' {
  declare module.exports: any;
}

declare module 'polymathjs/src/index' {
  declare module.exports: any;
}

declare module 'polymathjs/src/IPFS' {
  declare module.exports: any;
}

declare module 'polymathjs/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polymathjs/dist/contracts/CappedSTOFactory.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/CappedSTOFactory'>;
}
declare module 'polymathjs/dist/contracts/Contract.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/Contract'>;
}
declare module 'polymathjs/dist/contracts/PermissionManager.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/PermissionManager'>;
}
declare module 'polymathjs/dist/contracts/PolyToken.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/PolyToken'>;
}
declare module 'polymathjs/dist/contracts/SecurityToken.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/SecurityToken'>;
}
declare module 'polymathjs/dist/contracts/SecurityTokenRegistrar.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/SecurityTokenRegistrar'>;
}
declare module 'polymathjs/dist/contracts/SecurityTokenRegistry.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/SecurityTokenRegistry'>;
}
declare module 'polymathjs/dist/contracts/STO.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/STO'>;
}
declare module 'polymathjs/dist/contracts/TickerRegistrar.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/TickerRegistrar'>;
}
declare module 'polymathjs/dist/contracts/TickerRegistry.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/TickerRegistry'>;
}
declare module 'polymathjs/dist/contracts/TransferManager.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/TransferManager'>;
}
declare module 'polymathjs/dist/contracts/types.js' {
  declare module.exports: $Exports<'polymathjs/dist/contracts/types'>;
}
declare module 'polymathjs/dist/index.js' {
  declare module.exports: $Exports<'polymathjs/dist/index'>;
}
declare module 'polymathjs/dist/IPFS.js' {
  declare module.exports: $Exports<'polymathjs/dist/IPFS'>;
}
declare module 'polymathjs/flow-typed/npm/axios_v0.16.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/axios_v0.16.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-syntax-async-functions_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-transform-regenerator_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/bignumber.js_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/bignumber.js_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/eslint-plugin-polymath_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/eslint-plugin-polymath_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/npm-run-all_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/npm-run-all_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/polymath-core_v2_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/polymath-core_v2_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/redux-thunk_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/redux-thunk_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/web3_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/web3_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/web3-core-method_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/web3-core-method_vx.x.x'>;
}
declare module 'polymathjs/flow-typed/npm/web3-eth-contract_vx.x.x.js' {
  declare module.exports: $Exports<'polymathjs/flow-typed/npm/web3-eth-contract_vx.x.x'>;
}
declare module 'polymathjs/src/contracts/CappedSTOFactory.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/CappedSTOFactory'>;
}
declare module 'polymathjs/src/contracts/Contract.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/Contract'>;
}
declare module 'polymathjs/src/contracts/PermissionManager.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/PermissionManager'>;
}
declare module 'polymathjs/src/contracts/PolyToken.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/PolyToken'>;
}
declare module 'polymathjs/src/contracts/SecurityToken.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/SecurityToken'>;
}
declare module 'polymathjs/src/contracts/SecurityTokenRegistry.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/SecurityTokenRegistry'>;
}
declare module 'polymathjs/src/contracts/STO.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/STO'>;
}
declare module 'polymathjs/src/contracts/TickerRegistry.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/TickerRegistry'>;
}
declare module 'polymathjs/src/contracts/TransferManager.js' {
  declare module.exports: $Exports<'polymathjs/src/contracts/TransferManager'>;
}
declare module 'polymathjs/src/index.js' {
  declare module.exports: $Exports<'polymathjs/src/index'>;
}
declare module 'polymathjs/src/IPFS.js' {
  declare module.exports: $Exports<'polymathjs/src/IPFS'>;
}
declare module 'polymathjs/types.js' {
  declare module.exports: $Exports<'polymathjs/types'>;
}
